(1; 'Første plante'; 'Latinsk navn'; 'fugiat quo voluptas nulla pariatu.')
(2; 'Anden plante'; 'Latinsk navn'; 'et aut officiis debitis autuptates repudiandae, sint et molestiae non recusandae.')
(3; 'Anden plante'; 'Latinsk navn'; 'et aut officiis debitis autuptates repudiandae, sint et molestiae non recusandae.')
(4; 'Anden plante'; 'Latinsk navn'; 'et aut officiis debitis autuptates repudiandae, sint et molestiae non recusandae.')
(5; 'Anden plante'; 'Latinsk navn'; 'et aut officiis debitis autuptates repudiandae, sint et molestiae non recusandae.')